sudo: required
services:
    - docker
    
before_install:
    - docker build -t gerhsa/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true gerhsa/docker-react npm run test